### ISSUE TITLE
Sampler incompatible with TensorRT engine?

### ISSUE THREAD

**Issue by PmNz8** [Koishi-Star/Euler-Smea-Dyn-Sampler#18]
Hello. I installed your sampler in automatic1111 stable-diffusion-webui.

It works fine as long as I use standard engine. I also use TensorRT from here:
https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT

When I build engine it works with other samplers but fails to work with either Euler Dy or Euler SMEA Dy.

I do not know if the issue is caused by sampler incompatiblity with TensorRT or the other way around, so I decided to start by creating the issue here, I hope you do not mind. Below is what I get in my console during the error.

My system is Windows 10 x64, RTX 4090 with newest drivers and up-to-date sd-webui.

*** Error running process: C:\Users\n\Downloads\sd.webui\webui\extensions\Stable-Diffusion-WebUI-TensorRT\scripts\trt.py
    Traceback (most recent call last):
      File "C:\Users\nrv\Downloads\sd.webui\webui\modules\scripts.py", line 825, in process
        script.process(p, *script_args)
      File "C:\Users\nrv\Downloads\sd.webui\webui\extensions\Stable-Diffusion-WebUI-TensorRT\scripts\trt.py", line 255, in process
        self.idx, self.hr_idx = self.get_profile_idx(p, p.sd_model_name, ModelType.UNET)
      File "C:\Users\nrv\Downloads\sd.webui\webui\extensions\Stable-Diffusion-WebUI-TensorRT\scripts\trt.py", line 152, in get_profile_idx
        ) = modelmanager.get_valid_models(
      File "C:\Users\nrv\Downloads\sd.webui\webui\extensions\Stable-Diffusion-WebUI-TensorRT\model_manager.py", line 225, in get_valid_models
        for i, model in enumerate(models[base_model]):
    KeyError: 'ponyDiffusionV6XL_v6StartWithThisOne'

```
---
  0%|                                                                                                                                                                                                     | 0/64 [00:00<?, ?it/s][E] 3: [executionContext.cpp::nvinfer1::rt::ExecutionContext::validateInputBindings::2045] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::nvinfer1::rt::ExecutionContext::validateInputBindings::2045, condition: profileMaxDims.d[i] >= dimensions.d[i]. Supplied binding dimension [2,4,160,160] for bindings[0] exceed min ~ max range at index 2, maximum dimension in profile is 128, minimum dimension in profile is 128, but supplied dimension is 160.
    )
  0%|                                                                                                                                                                                                     | 0/64 [00:00<?, ?it/s]
*** Error completing request
*** Arguments: ('task(r41vdqjxokxlbt0)', <gradio.routes.Request object at 0x000002010F05DDE0>, 'solo anthro female zebra with clothes and simple white background, anime style', 'pink color', [], 1, 1, 5, 1024, 1024, False, 0.7, 2, 'Latent', 0, 0, 0, 'Use same checkpoint', 'Use same sampler', 'Use same scheduler', '', '', [], 0, 64, 'Euler SMEA Dy', 'SGM Uniform', False, '', 0.8, 266253257, False, -1, 0, 0, 0, False, False, 'positive', 'comma', 0, False, False, 'start', '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, False, False, False, 0, False) {}
    Traceback (most recent call last):
      File "C:\Users\nrv\Downloads\sd.webui\webui\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "C:\Users\nrv\Downloads\sd.webui\webui\modules\call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "C:\Users\nrv\Downloads\sd.webui\webui\modules\txt2img.py", line 109, in txt2img
        processed = processing.process_images(p)
      File "C:\Users\nrv\Downloads\sd.webui\webui\modules\processing.py", line 845, in process_images
        res = process_images_inner(p)
      File "C:\Users\nrv\Downloads\sd.webui\webui\modules\processing.py", line 981, in process_images_inner
        samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
      File "C:\Users\nrv\Downloads\sd.webui\webui\modules\processing.py", line 1328, in sample
        samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
      File "C:\Users\nrv\Downloads\sd.webui\webui\modules\sd_samplers_kdiffusion.py", line 218, in sample
        samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
      File "C:\Users\nrv\Downloads\sd.webui\webui\modules\sd_samplers_common.py", line 272, in launch_sampling
        return func()
      File "C:\Users\nrv\Downloads\sd.webui\webui\modules\sd_samplers_kdiffusion.py", line 218, in <lambda>
        samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
      File "C:\Users\nrv\Downloads\sd.webui\system\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "C:\Users\nrv\Downloads\sd.webui\webui\extensions\Euler-Smea-Dyn-Sampler\smea_sampling.py", line 163, in sample_euler_smea_dy
        x = smea_sampling_step(x, model, dt, sigma_hat, **extra_args)
      File "C:\Users\nrv\Downloads\sd.webui\system\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "C:\Users\nrv\Downloads\sd.webui\webui\extensions\Euler-Smea-Dyn-Sampler\smea_sampling.py", line 136, in smea_sampling_step
        denoised = model(x, sigma_hat * x.new_ones([x.shape[0]]), **rescaler.extra_args)
      File "C:\Users\nrv\Downloads\sd.webui\system\python\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "C:\Users\nrv\Downloads\sd.webui\webui\modules\sd_samplers_cfg_denoiser.py", line 237, in forward
        x_out = self.inner_model(x_in, sigma_in, cond=make_condition_dict(cond_in, image_cond_in))
      File "C:\Users\nrv\Downloads\sd.webui\system\python\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "C:\Users\nrv\Downloads\sd.webui\webui\repositories\k-diffusion\k_diffusion\external.py", line 113, in forward
        return input + eps * c_out
    RuntimeError: The size of tensor a (160) must match the size of tensor b (128) at non-singleton dimension 3

---
```

**Comment by Koishi-Star** [comment]
I'm afraid I can't do anything about it. TensorRT works very differently,   

 I don't mean this with any ill will or jealousy, but TensorRT doesn't offer significant improvements for the 4090, and its acceleration effect is minimal for small batch image generation.

But I still wish you find a solution soon. I will, if I have enough time, try to fix it.
