### ISSUE TITLE
New Kohaku_LoNyu_Yog sampler won't load

### ISSUE THREAD

**Issue by Kasr40k** [Koishi-Star/Euler-Smea-Dyn-Sampler#28]
I can't use the newly added sampler. Here's the error message displayed by the log:

**!!! Exception during processing !!! module 'comfy.k_diffusion.sampling' has no attribute 'sample_sample_Kohaku_LoNyu_Yog'
Traceback (most recent call last):
  File "C:\Users\ATARY\ComfyUI_windows_portable\ComfyUI\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ATARY\ComfyUI_windows_portable\ComfyUI\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ATARY\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\Users\ATARY\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ATARY\ComfyUI_windows_portable\ComfyUI\comfy_extras\nodes_custom_sampler.py", line 226, in get_sampler
    sampler = comfy.samplers.sampler_object(sampler_name)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ATARY\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 762, in sampler_object
    sampler = ksampler(name)
              ^^^^^^^^^^^^^^
  File "C:\Users\ATARY\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 628, in ksampler
    sampler_function = getattr(k_diffusion_sampling, "sample_{}".format(sampler_name))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'comfy.k_diffusion.sampling' has no attribute 'sample_sample_Kohaku_LoNyu_Yog'**

**Comment by MythicalChu** [comment]
I found the error:
on __init__.py, on SAMPLER_NAMES.append("sample_Kohaku_LoNyu_Yog"), delete "sample_", it should be just the name of the sampler like the above ones are.

Damn, this sampler is heavy!

**Comment by Kasr40k** [comment]
Thanks! That solved the error. The author should apply that correction whenever they can
